# Generated by Django 4.2.23 on 2025-08-09 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Masalalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mavzu', models.CharField(max_length=255)),
                ('tartib_raqami', models.PositiveIntegerField()),
                ('word_file', models.FileField(upload_to='masalalar/word_fayllar/')),
            ],
            options={
                'ordering': ['tartib_raqami'],
            },
        ),
        migrations.CreateModel(
            name='NazariyMavzular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mavzu', models.CharField(max_length=255)),
                ('tartib_raqami', models.PositiveIntegerField()),
                ('word_file', models.FileField(upload_to='nazariy_mavzular/word_fayllar/')),
                ('html_file', models.FileField(upload_to='nazariy_mavzular/html/')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=255)),
                ('tartib_raqami', models.PositiveIntegerField()),
                ('nazariy_mavzu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testlar', to='main.nazariymavzular')),
            ],
            options={
                'ordering': ['tartib_raqami'],
            },
        ),
        migrations.CreateModel(
            name='Videolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=255)),
                ('tartib_raqami', models.PositiveIntegerField()),
                ('video_file', models.FileField(help_text='Faqat .mp4 formatdagi video yuklang.', upload_to='videolar/video_fayllar/')),
                ('yakunlangan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('nazariy_mavzu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videolar', to='main.nazariymavzular')),
            ],
            options={
                'ordering': ['tartib_raqami'],
            },
        ),
        migrations.CreateModel(
            name='TestSavol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol_matni', models.TextField()),
                ('variant_a', models.CharField(max_length=255)),
                ('variant_b', models.CharField(max_length=255)),
                ('variant_c', models.CharField(max_length=255)),
                ('variant_d', models.CharField(max_length=255)),
                ('togri_javob', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savollar', to='main.test')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TestNatija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('togri_savollar_soni', models.PositiveIntegerField()),
                ('jami_savollar_soni', models.PositiveIntegerField()),
                ('foiz', models.FloatField()),
                ('yakunlangan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('foydalanuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_natijalari', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natijalar', to='main.test')),
            ],
        ),
        migrations.CreateModel(
            name='AmaliyMavzular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mavzu', models.CharField(max_length=255)),
                ('tartib_raqami', models.PositiveIntegerField()),
                ('word_file', models.FileField(upload_to='amaliy_mavzular/word_fayllar/')),
                ('html_file', models.FileField(upload_to='amaliy_mavzular/html/')),
                ('nazariy_mavzu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amaliy_mavzular', to='main.nazariymavzular')),
            ],
        ),
    ]
