# Generated by Django 4.2.23 on 2025-08-09 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amaliymavzular',
            name='nazariy_mavzu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amaliy_mavzular', to='main.nazariymavzular'),
        ),
    ]
