# Generated by Django 4.2.23 on 2025-08-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_amaliymavzular_nazariy_mavzu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masalalar',
            options={},
        ),
        migrations.AddField(
            model_name='masalalar',
            name='html_file',
            field=models.FileField(default=-1, upload_to='masalalar/html/'),
            preserve_default=False,
        ),
    ]
