# Generated by Django 4.2.23 on 2025-08-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_masalalar_options_masalalar_html_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='testnatija',
            name='grade',
            field=models.CharField(default=-1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testnatija',
            name='no_togri_savollar_soni',
            field=models.PositiveIntegerField(default=-1),
            preserve_default=False,
        ),
    ]
