# Generated by Django 4.2.23 on 2025-08-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_testnatija_grade_testnatija_no_togri_savollar_soni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsavol',
            name='variant_a',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testsavol',
            name='variant_b',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testsavol',
            name='variant_c',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testsavol',
            name='variant_d',
            field=models.TextField(max_length=255),
        ),
    ]
