# Generated by Django 4.2.23 on 2025-08-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_testsavol_variant_a_alter_testsavol_variant_b_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolar',
            name='video_file',
        ),
        migrations.AddField(
            model_name='videolar',
            name='video_url',
            field=models.URLField(default=-1, help_text='Google Drive link: https://drive.google.com/file/d/FILE_ID/view?usp=sharing'),
            preserve_default=False,
        ),
    ]
